package es.jvbabi.vplanplus.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val purple_md_theme_light_primary = Color(0xFF9A25AE)
val purple_md_theme_light_onPrimary = Color(0xFFFFFFFF)
val purple_md_theme_light_primaryContainer = Color(0xFFFFD6FE)
val purple_md_theme_light_onPrimaryContainer = Color(0xFF35003F)
val purple_md_theme_light_secondary = Color(0xFF6B586B)
val purple_md_theme_light_onSecondary = Color(0xFFFFFFFF)
val purple_md_theme_light_secondaryContainer = Color(0xFFF4DBF1)
val purple_md_theme_light_onSecondaryContainer = Color(0xFF251626)
val purple_md_theme_light_tertiary = Color(0xFF82524A)
val purple_md_theme_light_onTertiary = Color(0xFFFFFFFF)
val purple_md_theme_light_tertiaryContainer = Color(0xFFFFDAD4)
val purple_md_theme_light_onTertiaryContainer = Color(0xFF33110C)
val purple_md_theme_light_error = Color(0xFFBA1A1A)
val purple_md_theme_light_errorContainer = Color(0xFFFFDAD6)
val purple_md_theme_light_onError = Color(0xFFFFFFFF)
val purple_md_theme_light_onErrorContainer = Color(0xFF410002)
val purple_md_theme_light_background = Color(0xFFFFFBFF)
val purple_md_theme_light_onBackground = Color(0xFF1E1A1D)
val purple_md_theme_light_surface = Color(0xFFFFFBFF)
val purple_md_theme_light_onSurface = Color(0xFF1E1A1D)
val purple_md_theme_light_surfaceVariant = Color(0xFFECDFE8)
val purple_md_theme_light_onSurfaceVariant = Color(0xFF4D444C)
val purple_md_theme_light_outline = Color(0xFF7F747D)
val purple_md_theme_light_inverseOnSurface = Color(0xFFF7EEF3)
val purple_md_theme_light_inverseSurface = Color(0xFF332F32)
val purple_md_theme_light_inversePrimary = Color(0xFFF9ABFF)
val purple_md_theme_light_shadow = Color(0xFF000000)
val purple_md_theme_light_surfaceTint = Color(0xFF9A25AE)
val purple_md_theme_light_outlineVariant = Color(0xFFD0C3CC)
val purple_md_theme_light_scrim = Color(0xFF000000)

val purple_md_theme_dark_primary = Color(0xFFF9ABFF)
val purple_md_theme_dark_onPrimary = Color(0xFF570066)
val purple_md_theme_dark_primaryContainer = Color(0xFF7B008F)
val purple_md_theme_dark_onPrimaryContainer = Color(0xFFFFD6FE)
val purple_md_theme_dark_secondary = Color(0xFFD7BFD5)
val purple_md_theme_dark_onSecondary = Color(0xFF3B2B3C)
val purple_md_theme_dark_secondaryContainer = Color(0xFF534153)
val purple_md_theme_dark_onSecondaryContainer = Color(0xFFF4DBF1)
val purple_md_theme_dark_tertiary = Color(0xFFF6B8AD)
val purple_md_theme_dark_onTertiary = Color(0xFF4C251F)
val purple_md_theme_dark_tertiaryContainer = Color(0xFF673B34)
val purple_md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD4)
val purple_md_theme_dark_error = Color(0xFFFFB4AB)
val purple_md_theme_dark_errorContainer = Color(0xFF93000A)
val purple_md_theme_dark_onError = Color(0xFF690005)
val purple_md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val purple_md_theme_dark_background = Color(0xFF1E1A1D)
val purple_md_theme_dark_onBackground = Color(0xFFE9E0E4)
val purple_md_theme_dark_surface = Color(0xFF1E1A1D)
val purple_md_theme_dark_onSurface = Color(0xFFE9E0E4)
val purple_md_theme_dark_surfaceVariant = Color(0xFF4D444C)
val purple_md_theme_dark_onSurfaceVariant = Color(0xFFD0C3CC)
val purple_md_theme_dark_outline = Color(0xFF998D96)
val purple_md_theme_dark_inverseOnSurface = Color(0xFF1E1A1D)
val purple_md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val purple_md_theme_dark_inversePrimary = Color(0xFF9A25AE)
val purple_md_theme_dark_shadow = Color(0xFF000000)
val purple_md_theme_dark_surfaceTint = Color(0xFFF9ABFF)
val purple_md_theme_dark_outlineVariant = Color(0xFF4D444C)
val purple_md_theme_dark_scrim = Color(0xFF000000)

val purple_seed = Color(0xFF9C27B0)

val purple_light = lightColorScheme(
    primary = purple_md_theme_light_primary,
    onPrimary = purple_md_theme_light_onPrimary,
    primaryContainer = purple_md_theme_light_primaryContainer,
    onPrimaryContainer = purple_md_theme_light_onPrimaryContainer,
    secondary = purple_md_theme_light_secondary,
    onSecondary = purple_md_theme_light_onSecondary,
    secondaryContainer = purple_md_theme_light_secondaryContainer,
    onSecondaryContainer = purple_md_theme_light_onSecondaryContainer,
    tertiary = purple_md_theme_light_tertiary,
    onTertiary = purple_md_theme_light_onTertiary,
    tertiaryContainer = purple_md_theme_light_tertiaryContainer,
    onTertiaryContainer = purple_md_theme_light_onTertiaryContainer,
    error = purple_md_theme_light_error,
    errorContainer = purple_md_theme_light_errorContainer,
    onError = purple_md_theme_light_onError,
    onErrorContainer = purple_md_theme_light_onErrorContainer,
    background = purple_md_theme_light_background,
    onBackground = purple_md_theme_light_onBackground,
    surface = purple_md_theme_light_surface,
    onSurface = purple_md_theme_light_onSurface,
    surfaceVariant = purple_md_theme_light_surfaceVariant,
    onSurfaceVariant = purple_md_theme_light_onSurfaceVariant,
    outline = purple_md_theme_light_outline,
    inverseOnSurface = purple_md_theme_light_inverseOnSurface,
    inverseSurface = purple_md_theme_light_inverseSurface,
    inversePrimary = purple_md_theme_light_inversePrimary,
    surfaceTint = purple_md_theme_light_surfaceTint,
    outlineVariant = purple_md_theme_light_outlineVariant,
    scrim = purple_md_theme_light_scrim,
)

val purple_dark = darkColorScheme(
    primary = purple_md_theme_dark_primary,
    onPrimary = purple_md_theme_dark_onPrimary,
    primaryContainer = purple_md_theme_dark_primaryContainer,
    onPrimaryContainer = purple_md_theme_dark_onPrimaryContainer,
    secondary = purple_md_theme_dark_secondary,
    onSecondary = purple_md_theme_dark_onSecondary,
    secondaryContainer = purple_md_theme_dark_secondaryContainer,
    onSecondaryContainer = purple_md_theme_dark_onSecondaryContainer,
    tertiary = purple_md_theme_dark_tertiary,
    onTertiary = purple_md_theme_dark_onTertiary,
    tertiaryContainer = purple_md_theme_dark_tertiaryContainer,
    onTertiaryContainer = purple_md_theme_dark_onTertiaryContainer,
    error = purple_md_theme_dark_error,
    errorContainer = purple_md_theme_dark_errorContainer,
    onError = purple_md_theme_dark_onError,
    onErrorContainer = purple_md_theme_dark_onErrorContainer,
    background = purple_md_theme_dark_background,
    onBackground = purple_md_theme_dark_onBackground,
    surface = purple_md_theme_dark_surface,
    onSurface = purple_md_theme_dark_onSurface,
    surfaceVariant = purple_md_theme_dark_surfaceVariant,
    onSurfaceVariant = purple_md_theme_dark_onSurfaceVariant,
    outline = purple_md_theme_dark_outline,
    inverseOnSurface = purple_md_theme_dark_inverseOnSurface,
    inverseSurface = purple_md_theme_dark_inverseSurface,
    inversePrimary = purple_md_theme_dark_inversePrimary,
    surfaceTint = purple_md_theme_dark_surfaceTint,
    outlineVariant = purple_md_theme_dark_outlineVariant,
    scrim = purple_md_theme_dark_scrim,
)