name: Build Release
on:
  push:
    branches:
      - ci

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Generate Keystore
              run: echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks
            - name: Build Release AAB
              run: ./gradlew :app:bundleRelease
            - name: Build Release APK
              run: ./gradlew :app:assembleRelease
            - name: Upload Release AAB
              uses: actions/upload-artifact@v4
              with:
                name: AAB
                path: app/build/outputs/bundle/release/app-release.aab

            - name: Upload Release APK
              uses: actions/upload-artifact@v4
              with:
                name: APK
                path: app/build/outputs/apk/release/app-release.apk